//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bobbySaxyKennel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class OrderCard
    {
        public int Id { get; set; }
        public string Name { get; set; }
        public string Number { get; set; }
        public string CCV { get; set; }
        public string ExpireDate { get; set; }
        public string MoreInfo { get; set; }
        public Nullable<System.DateTime> DateAdded { get; set; }
    }
}
