//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace bobbySaxyKennel.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class QuotaReply
    {
        public int ID { get; set; }
        public string Message { get; set; }
        public System.DateTime DateTime { get; set; }
        public int QuotaID { get; set; }
    
        public virtual QuotaMessage QuotaMessage { get; set; }
    }
}
